version: '4.6.13'

services:
  postgres_lab23:
    container_name: postgres_lab23
    image: postgres:15
    env_file:
      - .local.env
    ports:
      - 5432:5432
    restart: always

  redis_lab23: 
    container_name: redis_lab23
    image: redis
    ports:
      - 6379:6379